export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';
export const FETCH_SECTIONS = 'FETCH_SECTIONS';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';

export const FLAG_TEST_INITIALIZED = 'FLAG_TEST_INITIALIZED';

export const FETCH_TEST_LOG_SUMMARY = 'FETCH_TESTLOGSUMMARY';
export const FETCH_TEST_LOG_GRANULAR = 'FETCH_TESTLOGGRANULAR';
export const TEST_LOG_CLEAR_GRANULAR = 'TEST_LOG_CLEAR_GRANULAR';

export const FETCH_PROPOSED_QUESTIONS = 'FETCH_PROPOSED_QUESTIONS';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';