# Generated by Django 2.1 on 2018-08-19 17:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionType',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='section',
        ),
    ]
