# Generated by Django 2.1.1 on 2018-09-24 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0009_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('correctAnswers', models.IntegerField()),
                ('totalQuestions', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logTestUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logTestAnswer', to='question.Answer')),
                ('logTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logTest', to='question.LogTest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logTestQuestion', to='question.Question')),
            ],
        ),
    ]
